//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/UI/Inventory/UIControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIControls"",
    ""maps"": [
        {
            ""name"": ""UIActionMap"",
            ""id"": ""c6a3c3a3-a9b4-4562-a45a-a83d0e3d1ade"",
            ""actions"": [
                {
                    ""name"": ""InventoryCloseOpen"",
                    ""type"": ""Button"",
                    ""id"": ""29e5e4de-a516-4e6f-a16a-5ebb53127fed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3ebad1fe-ccd1-4b66-a838-cd4bd14a4d3f"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryCloseOpen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UIActionMap
        m_UIActionMap = asset.FindActionMap("UIActionMap", throwIfNotFound: true);
        m_UIActionMap_InventoryCloseOpen = m_UIActionMap.FindAction("InventoryCloseOpen", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UIActionMap
    private readonly InputActionMap m_UIActionMap;
    private IUIActionMapActions m_UIActionMapActionsCallbackInterface;
    private readonly InputAction m_UIActionMap_InventoryCloseOpen;
    public struct UIActionMapActions
    {
        private @UIControls m_Wrapper;
        public UIActionMapActions(@UIControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @InventoryCloseOpen => m_Wrapper.m_UIActionMap_InventoryCloseOpen;
        public InputActionMap Get() { return m_Wrapper.m_UIActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IUIActionMapActions instance)
        {
            if (m_Wrapper.m_UIActionMapActionsCallbackInterface != null)
            {
                @InventoryCloseOpen.started -= m_Wrapper.m_UIActionMapActionsCallbackInterface.OnInventoryCloseOpen;
                @InventoryCloseOpen.performed -= m_Wrapper.m_UIActionMapActionsCallbackInterface.OnInventoryCloseOpen;
                @InventoryCloseOpen.canceled -= m_Wrapper.m_UIActionMapActionsCallbackInterface.OnInventoryCloseOpen;
            }
            m_Wrapper.m_UIActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @InventoryCloseOpen.started += instance.OnInventoryCloseOpen;
                @InventoryCloseOpen.performed += instance.OnInventoryCloseOpen;
                @InventoryCloseOpen.canceled += instance.OnInventoryCloseOpen;
            }
        }
    }
    public UIActionMapActions @UIActionMap => new UIActionMapActions(this);
    public interface IUIActionMapActions
    {
        void OnInventoryCloseOpen(InputAction.CallbackContext context);
    }
}
